# Select the waypoints using indexes
# double xpos[] = {2.093, 3.936, 5.602,	 7.567,	7.483,	5.806, 4.405, 2.914, 1.208, 1.014, 1.305, 2.150};
# double ypos[] = {7.419, 7.199, 7.409,	 5.951,	3.926,	2.396, 1.069, 1.386, 0.978, 2.683, 4.224, 5.739};
      
--- name:default
# List containing indexes of selected waypoints
selectedWaypoints: [1, 2, 4, 8, 9]

--- name:bigloop
# List containing indexes of selected waypoints
selectedWaypoints: [1, 2, 3, 8, 12, 16, 20, 19, 19, 13, 9, 5]

--- name:smallloop
# List containing indexes of selected waypoints
selectedWaypoints: [5, 6, 11, 16, 20, 19, 13, 9, 5]

--- name:doubleloop
# List containing indexes of selected waypoints
selectedWaypoints: [5, 6, 11, 15, 14, 13, 9, 5, 6, 11, 15, 14, 13, 9, 5]

--- name:short
# List containing indexes of selected waypoints
selectedWaypoints: [1]


