   
--- name:default
# List containing indexes of selected waypoints
selectedWaypoints: [1, 2, 4, 8, 9]
goal_heading: 0.0

--- name:bigloop
# List containing indexes of selected waypoints
selectedWaypoints: [1, 2, 3, 8, 12, 16, 20, 19, 19, 13, 9, 5]
goal_heading: 0.0

--- name:smallloop
# List containing indexes of selected waypoints
selectedWaypoints: [5, 6, 11, 16, 20, 19, 13, 9, 5]
goal_heading: 0.0

--- name:doubleloop
# List containing indexes of selected waypoints
selectedWaypoints: [5, 6, 11, 15, 14, 13, 9, 5, 6, 11, 15, 14, 13, 9, 5]
goal_heading: 0.0

--- name:short
# List containing indexes of selected waypoints
selectedWaypoints: [1]
goal_heading: 90.0

--- name:demoloop
# List containing indexes of selected waypoints
selectedWaypoints: [1, 2, 7, 11, 16, 20, 19, 13, 9, 1]
goal_heading: 0.0

--- name:prl
# Lists containing x-coordinates of available waypoints
xpos: [2.093, 3.936, 5.602, 7.834, 2.150, 3.906, 5.843, 7.567, 0.705, 4.283, 5.741, 7.483, 1.014, 2.950, 4.300, 5.806, 7.227, 1.208, 2.914, 4.405, 7.051]
# Lists containing y-coordinates of available waypoints
ypos: [7.419, 7.199, 7.409, 7.899, 5.739, 5.781, 5.952, 5.951, 4.224, 4.015, 3.961, 3.926, 2.683, 2.549, 2.388, 2.396, 2.404, 0.978, 1.386, 1.069, 1.132]

