--- name:default
# Configuration of Path Tracker parameters, namely distances, velocities and turn radius
ptConfig:
  minTurnRadius: 0.6
  translationalVelocity: 0.05
  rotationalVelocity: 0.15
  corridor: 0.2
  maxDisalignment: 0.15
  lookaheadDistance: 0.60
  backwards: false
  

--- name:exoter
# Configuration of Path Tracker parameters, namely distances, velocities and turn radius
ptConfig:
  minTurnRadius: 0.6
  translationalVelocity: 0.05
  rotationalVelocity: 0.15
  corridor: 0.2
  maxDisalignment: 0.15
  lookaheadDistance: 0.50
  backwards: false

